# Generated by Django 3.2.9 on 2021-12-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameAlbum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='cover/')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='cover/')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('song', models.FileField(null=True, upload_to='')),
                ('album', models.CharField(max_length=255)),
                ('release', models.DateField(default='19-12-2021')),
                ('image', models.ImageField(null=True, upload_to='cover/')),
                ('like', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
            ],
        ),
    ]
