# Generated by Django 3.2.9 on 2021-12-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20211219_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songs',
            name='release',
            field=models.DateField(default='20-12-2021'),
        ),
    ]
